### ISSUE TITLE
Sql Error on page after upgrade from 0.2.0 to 0.3.0

### ISSUE THREAD

**Issue by jawood1** [jcdcdev/jcdcdev.Umbraco.ReadingTime#9]
### Which jcdcdev.Umbraco.ReadingTime version are you using?

0.3.0

### Which Umbraco version are you using? For example: 10.4.0 - don't just write v10

13.2.2

### Bug summary

Hello me again :)

We've just implemented your latest version of the package but seem to encounter an SQL related error on the page it's being used on.

Removing the property we found the page worked correctly again, we've downgraded to 0.2.0 for now.

Please fine relevant info and stacktrace below:

CMS:
![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/47325234/d112d23e-7282-41ca-aa59-d3a7e76a4372)

Configuration:
With vary by culture
![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/47325234/8a2ea45c-ee43-40c7-afa2-fbdf352db081)

Stacktrace:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'dataTypeKey'.

Invalid column name 'dataTypeKey'.

Invalid column name 'dataTypeId'.

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)

   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)

   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 204

   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)

   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)

--- End of stack trace from previous location ---

   at NPoco.Database.ExecutionHookAsync[T](Func`1 action)

   at NPoco.Database.ExecuteReaderHelperAsync(DbCommand cmd)

   at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

   at NPoco.Database.QueryAsync[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

   at NPoco.Database.QueryAsync[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36

   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36

   at jcdcdev.Umbraco.ReadingTime.Infrastructure.Persistence.ReadingTimeRepository.Get(Guid key, Guid dataTypeKey)

ClientConnectionId:49aa5ad5-d45f-4b0c-8ec4-c7614f65ce3e

Error Number:207,State:1,Class:16
```

Please find 

### Steps to reproduce

1. Add the readtime datatype to a page field
2. Going to the page or creating a new one causes the error to occur
3. Can't proceed further

### Expected result / actual result

Page to display without error

**Comment by jcdcdev** [comment]
Uh oh, that's no good! Sorry for the inconvenience, it looks like the latest db migration has not run.

A quick work around (if you're confident) would be to clear the umbracoKeyValue row that corresponds to this package. Reboot the site and the migration should run (this will clear existing reading time data) 

I'm on my mobile but will update this issue later tonight with a workaround and (hopefully) even a fixed version!

**Comment by jawood1** [comment]
Hi @jcdcdev 

Great thank you I'll take a look at that workaround and see if it resolves the issue. Thanks for responding so quickly!

**Comment by jcdcdev** [comment]
Hi @jawood1 I've pushed an updated version that will drop and recreate the table responsible for holding reading time data.

This will ensure the expected columns exist.

If you still experience this error on 0.3.1 please could you tell me what you see in the "Installed Packages" section for this package?

You should expect to see "All package migrations have successfully completed."

![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/23620443/419f83bc-0da2-4cd7-8999-a9f6ced326b1)

If not, you will be given the option to run the migrations there, please provide any logs if an error occurs.

![image](https://github.com/jcdcdev/jcdcdev.Umbraco.ReadingTime/assets/23620443/8de56d16-5ca9-4340-9620-983338b2cad8)

**Comment by jcdcdev** [comment]
Awesome news! ☺
